## Filtrar usando .apply
Se puede utilizar las bondades de .apply para hacer filtros complicados.

In [1]:
import numpy as np # librería para operar matrices o arreglos
import pandas as pd # para manipular dataframe

print([[4, 9]] * 3)
df = pd.DataFrame([[4, 9]] * 3, columns=['A', 'B'])
print(type(df))
df

[[4, 9], [4, 9], [4, 9]]
<class 'pandas.DataFrame'>

   A  B
0  4  9
1  4  9
2  4  9

In [2]:
df.apply(np.sqrt)

     A    B
0  2.0  3.0
1  2.0  3.0
2  2.0  3.0

In [3]:
df.apply(np.mean, axis=1)

0    6.5
1    6.5
2    6.5
dtype: float64

In [10]:
df.apply(np.var, axis=1)

0    6.25
1    6.25
2    6.25
dtype: float64

In [4]:
## Leyendo conjunto de datos Iris y colocando nombre a las columnas:
iris = pd.read_csv('http://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data',sep = ",", header = None)
names = ["sepalo_longitud", "sepalo_ancho", "petalo_longitud", "petalo_ancho", "clase"]
iris.columns = names
print(iris.head())
iris.info()

   sepalo_longitud  sepalo_ancho  petalo_longitud  petalo_ancho        clase
0              5.1           3.5              1.4           0.2  Iris-setosa
1              4.9           3.0              1.4           0.2  Iris-setosa
2              4.7           3.2              1.3           0.2  Iris-setosa
3              4.6           3.1              1.5           0.2  Iris-setosa
4              5.0           3.6              1.4           0.2  Iris-setosa
<class 'pandas.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   sepalo_longitud  150 non-null    float64
 1   sepalo_ancho     150 non-null    float64
 2   petalo_longitud  150 non-null    float64
 3   petalo_ancho     150 non-null    float64
 4   clase            150 non-null    str
dtypes: float64(4), str(1)
memory usage: 6.0 KB

In [10]:
iris['sepalo_ancho'].apply(np.mean,axis=1)

AxisError: axis 1 is out of bounds for array of dimension 0

In [16]:
#iris[iris['sepalo_ancho']>3].apply(np.sum,axis=0)
iris.loc[iris['sepalo_ancho']>3,"petalo_longitud":"petalo_ancho"].apply(np.mean, axis=0)
#[iris['sepalo_ancho']>3,"sepalo_longitud":"petalo_ancho"]
#iris[iris['sepalo_ancho']>3].apply(np.sum, axis=0)

petalo_longitud    2.935821
petalo_ancho       0.905970
dtype: float64

# Compresión de Lista
Es una forma concisa y eficiente de crear listas en Python. Permite generar una nueva lista aplicando una expresión a cada elemento de una secuencia o iterable, opcionalmente filtrando elementos con una condición.

La sintaxis básica es:
[expresion for elemento in iterable if condicion]

In [14]:
# Creando una lista de los cuadrados de los números del 1 al 10 usando list comprehension
cuadrados = [x**2 for x in range(1, 11)]
print(cuadrados)

# Creando una lista con los números pares del 1 al 100 multiplicado por 2 usando list comprehension# Creando un diccionario con los números del 1 al 10 y sus cuadrados usando dictionary comprehension
cuadrados_dict = {x: x**2 for x in range(1, 11)}
print(cuadrados_dict)
A = [i*2 for i in range(1, 101) if i % 2 == 0]
print(A)

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]
{1: 1, 2: 4, 3: 9, 4: 16, 5: 25, 6: 36, 7: 49, 8: 64, 9: 81, 10: 100}
[4, 8, 12, 16, 20, 24, 28, 32, 36, 40, 44, 48, 52, 56, 60, 64, 68, 72, 76, 80, 84, 88, 92, 96, 100, 104, 108, 112, 116, 120, 124, 128, 132, 136, 140, 144, 148, 152, 156, 160, 164, 168, 172, 176, 180, 184, 188, 192, 196, 200]

# Compresión de Diccionarios
 Es una forma concisa y eficiente de crear diccionarios en Python. Permite generar un nuevo diccionario aplicando una expresión a cada elemento de una secuencia o iterable, opcionalmente filtrando elementos con una condición.

La sintaxis básica es:
{clave: valor for elemento in iterable if condicion}

In [15]:
# Creando un diccionario con los números del 1 al 10 y sus cuadrados usando dictionary comprehension
cuadrados_dict = {x: x**2 for x in range(1, 11)}
print(cuadrados_dict)

{1: 1, 2: 4, 3: 9, 4: 16, 5: 25, 6: 36, 7: 49, 8: 64, 9: 81, 10: 100}

# Funciones Lambda
En Python, se usa  la palabra clave __lambda__ para declarar una función anónima, por lo que nos referimos a ellas como "funciones lambda". Una función anónima se refiere a una función declarada sin nombre. Aunque sintácticamente se ven diferentes, las funciones lambda se comportan de la misma manera que las funciones regulares que se declaran usando la palabra clave __def__

Las funciones lambda se utilizan cuando se necesita una función por un período corto de tiempo.

In [16]:
def producto(x,y):
    producto=x*y
    return(producto)

producto(5,2)

10

In [17]:
producto = lambda x, y : x * y
producto(5,3)

15

In [17]:
prod2 =lambda x:x.B*x.A
#def prod2(x):
#    return x.B*x.A
print(df)
prod2(df)

   A  B
0  4  9
1  4  9
2  4  9

0    36
1    36
2    36
dtype: int64

In [30]:
print(iris.iloc[:,0:4].apply(np.sum, axis=0))
print(iris[["sepalo_longitud", "sepalo_ancho", "petalo_longitud", "petalo_ancho"]].apply(np.sum,axis=0))
print(iris[["sepalo_longitud", "sepalo_ancho", "petalo_longitud", "petalo_ancho"]].apply(np.mean,axis=0))
iris.describe()

sepalo_longitud    876.5
sepalo_ancho       458.1
petalo_longitud    563.8
petalo_ancho       179.8
dtype: float64
sepalo_longitud    876.5
sepalo_ancho       458.1
petalo_longitud    563.8
petalo_ancho       179.8
dtype: float64
sepalo_longitud    5.843333
sepalo_ancho       3.054000
petalo_longitud    3.758667
petalo_ancho       1.198667
dtype: float64

       sepalo_longitud  sepalo_ancho  petalo_longitud  petalo_ancho
count       150.000000    150.000000       150.000000    150.000000
mean          5.843333      3.054000         3.758667      1.198667
std           0.828066      0.433594         1.764420      0.763161
min           4.300000      2.000000         1.000000      0.100000
25%           5.100000      2.800000         1.600000      0.300000
50%           5.800000      3.000000         4.350000      1.300000
75%           6.400000      3.300000         5.100000      1.800000
max           7.900000      4.400000         6.900000      2.500000

In [42]:
print(iris.loc[iris.apply(lambda x: (x['sepalo_longitud'])>7, axis= 1)].describe())
iris.loc[iris['sepalo_longitud']>7].describe()

       sepalo_longitud  sepalo_ancho  petalo_longitud  petalo_ancho
count        12.000000     12.000000        12.000000     12.000000
mean          7.475000      3.125000         6.300000      2.050000
std           0.270101      0.398006         0.356753      0.254058
min           7.100000      2.600000         5.800000      1.600000
25%           7.200000      2.875000         6.075000      1.875000
50%           7.500000      3.000000         6.200000      2.050000
75%           7.700000      3.300000         6.625000      2.225000
max           7.900000      3.800000         6.900000      2.500000

       sepalo_longitud  sepalo_ancho  petalo_longitud  petalo_ancho
count        12.000000     12.000000        12.000000     12.000000
mean          7.475000      3.125000         6.300000      2.050000
std           0.270101      0.398006         0.356753      0.254058
min           7.100000      2.600000         5.800000      1.600000
25%           7.200000      2.875000         6.075000      1.875000
50%           7.500000      3.000000         6.200000      2.050000
75%           7.700000      3.300000         6.625000      2.225000
max           7.900000      3.800000         6.900000      2.500000

In [21]:
iris['clase']
iris.clase

0         Iris-setosa
1         Iris-setosa
2         Iris-setosa
3         Iris-setosa
4         Iris-setosa
            ...
145    Iris-virginica
146    Iris-virginica
147    Iris-virginica
148    Iris-virginica
149    Iris-virginica
Name: clase, Length: 150, dtype: object

In [22]:
iris.petalo_ancho.unique()
iris.clase

0         Iris-setosa
1         Iris-setosa
2         Iris-setosa
3         Iris-setosa
4         Iris-setosa
            ...
145    Iris-virginica
146    Iris-virginica
147    Iris-virginica
148    Iris-virginica
149    Iris-virginica
Name: clase, Length: 150, dtype: object

In [23]:
len(iris.petalo_ancho.unique())
len(iris.clase.unique())

3

In [24]:
# Crea una nueva columna con el nombre 'prom_petalo', la cual tiene el promedio de las medidas del ancho y longitud del petalo
iris = iris.assign(
prom_petalo= lambda x: (x.petalo_longitud+x.petalo_ancho)/2)
iris.head(5)

,sepalo_longitud,sepalo_ancho,petalo_longitud,petalo_ancho,clase,prom_petalo
0,5.1,3.5,1.4,0.2,Iris-setosa,0.80
1,4.9,3.0,1.4,0.2,Iris-setosa,0.80
2,4.7,3.2,1.3,0.2,Iris-setosa,0.75
3,4.6,3.1,1.5,0.2,Iris-setosa,0.85
4,5.0,3.6,1.4,0.2,Iris-setosa,0.80

In [25]:
# Crea una nueva columna con nombre 'prom_sepalo' usando .apply, la cual contiene el promedio de las medidas del 
# ancho y longitud del sepalo utilizando apply
iris['prom_sepalo'] = iris.apply(
lambda x: (x.sepalo_longitud+x.sepalo_ancho)/2, axis= 1)
iris.head(5)

,sepalo_longitud,sepalo_ancho,petalo_longitud,petalo_ancho,clase,prom_petalo,prom_sepalo
0,5.1,3.5,1.4,0.2,Iris-setosa,0.80,4.30
1,4.9,3.0,1.4,0.2,Iris-setosa,0.80,3.95
2,4.7,3.2,1.3,0.2,Iris-setosa,0.75,3.95
3,4.6,3.1,1.5,0.2,Iris-setosa,0.85,3.85
4,5.0,3.6,1.4,0.2,Iris-setosa,0.80,4.30

In [26]:
iris.head()
iris['prueba']=iris.petalo_longitud+2
iris.head()

,sepalo_longitud,sepalo_ancho,petalo_longitud,petalo_ancho,clase,prom_petalo,prom_sepalo,prueba
0,5.1,3.5,1.4,0.2,Iris-setosa,0.80,4.30,3.4
1,4.9,3.0,1.4,0.2,Iris-setosa,0.80,3.95,3.4
2,4.7,3.2,1.3,0.2,Iris-setosa,0.75,3.95,3.3
3,4.6,3.1,1.5,0.2,Iris-setosa,0.85,3.85,3.5
4,5.0,3.6,1.4,0.2,Iris-setosa,0.80,4.30,3.4

In [27]:
# borra una columna "in-place" (en el mismo marco de datos)
del iris['prom_sepalo']
iris.head(5)

,sepalo_longitud,sepalo_ancho,petalo_longitud,petalo_ancho,clase,prom_petalo,prueba
0,5.1,3.5,1.4,0.2,Iris-setosa,0.80,3.4
1,4.9,3.0,1.4,0.2,Iris-setosa,0.80,3.4
2,4.7,3.2,1.3,0.2,Iris-setosa,0.75,3.3
3,4.6,3.1,1.5,0.2,Iris-setosa,0.85,3.5
4,5.0,3.6,1.4,0.2,Iris-setosa,0.80,3.4

In [28]:
# borra 
iris2 = iris.drop(columns= ['prom_petalo', 'clase'])
iris2.head()

   sepalo_longitud  sepalo_ancho  petalo_longitud  petalo_ancho  prueba
0              5.1           3.5              1.4           0.2     3.4
1              4.9           3.0              1.4           0.2     3.4
2              4.7           3.2              1.3           0.2     3.3
3              4.6           3.1              1.5           0.2     3.5
4              5.0           3.6              1.4           0.2     3.4

In [29]:
#ordena los datos
iris.sort_values( "sepalo_longitud")

,sepalo_longitud,sepalo_ancho,petalo_longitud,petalo_ancho,clase,prom_petalo,prueba
13,4.3,3.0,1.1,0.1,Iris-setosa,0.60,3.1
42,4.4,3.2,1.3,0.2,Iris-setosa,0.75,3.3
38,4.4,3.0,1.3,0.2,Iris-setosa,0.75,3.3
8,4.4,2.9,1.4,0.2,Iris-setosa,0.80,3.4
41,4.5,2.3,1.3,0.3,Iris-setosa,0.80,3.3
...,...,...,...,...,...,...,...
122,7.7,2.8,6.7,2.0,Iris-virginica,4.35,8.7
118,7.7,2.6,6.9,2.3,Iris-virginica,4.60,8.9
117,7.7,3.8,6.7,2.2,Iris-virginica,4.45,8.7
135,7.7,3.0,6.1,2.3,Iris-virginica,4.20,8.1
131,7.9,3.8,6.4,2.0,Iris-virginica,4.20,8.4

In [30]:
#ordena los datos
iris.sort_values( "sepalo_longitud", ascending=False)

,sepalo_longitud,sepalo_ancho,petalo_longitud,petalo_ancho,clase,prom_petalo,prueba
131,7.9,3.8,6.4,2.0,Iris-virginica,4.20,8.4
135,7.7,3.0,6.1,2.3,Iris-virginica,4.20,8.1
122,7.7,2.8,6.7,2.0,Iris-virginica,4.35,8.7
117,7.7,3.8,6.7,2.2,Iris-virginica,4.45,8.7
118,7.7,2.6,6.9,2.3,Iris-virginica,4.60,8.9
...,...,...,...,...,...,...,...
41,4.5,2.3,1.3,0.3,Iris-setosa,0.80,3.3
42,4.4,3.2,1.3,0.2,Iris-setosa,0.75,3.3
38,4.4,3.0,1.3,0.2,Iris-setosa,0.75,3.3
8,4.4,2.9,1.4,0.2,Iris-setosa,0.80,3.4
13,4.3,3.0,1.1,0.1,Iris-setosa,0.60,3.1

In [31]:
iris.sort_values( ["sepalo_longitud", "sepalo_ancho"],ascending=[True,True])

,sepalo_longitud,sepalo_ancho,petalo_longitud,petalo_ancho,clase,prom_petalo,prueba
13,4.3,3.0,1.1,0.1,Iris-setosa,0.60,3.1
8,4.4,2.9,1.4,0.2,Iris-setosa,0.80,3.4
38,4.4,3.0,1.3,0.2,Iris-setosa,0.75,3.3
42,4.4,3.2,1.3,0.2,Iris-setosa,0.75,3.3
41,4.5,2.3,1.3,0.3,Iris-setosa,0.80,3.3
...,...,...,...,...,...,...,...
118,7.7,2.6,6.9,2.3,Iris-virginica,4.60,8.9
122,7.7,2.8,6.7,2.0,Iris-virginica,4.35,8.7
135,7.7,3.0,6.1,2.3,Iris-virginica,4.20,8.1
117,7.7,3.8,6.7,2.2,Iris-virginica,4.45,8.7
131,7.9,3.8,6.4,2.0,Iris-virginica,4.20,8.4

# Map
 Se utiliza para aplicar una función a cada elemento de un iterable (como una lista o un rango) y devolver un nuevo iterable con los resultados. La sintaxis básica es:
 
map(funcion, iterable)

In [32]:
# Usando map para crear una lista de los cuadrados de los números del 1 al 10
numeros = range(1, 11)
cuadrados = list(map(lambda x: x**2, numeros))
print(cuadrados)

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

In [33]:
numbers = [1, 2, 3, 4]
numbers_v2 = []
for i in numbers:
  numbers_v2.append(i * 2)

numbers_v3 = list(map(lambda i: i * 2, numbers))
print(numbers_v3)

[2, 4, 6, 8]

In [34]:
numero_1 = [1, 2, 3, 4]
numero_2 = [5, 6, 7]

print(numero_1)
print(numero_2)
result = list(map(lambda x, y: x + y, numero_1, numero_2))
print(result)

[1, 2, 3, 4]
[5, 6, 7]
[6, 8, 10]

In [35]:
items = [
  {
    'product': 'camisa',
    'price': 100,
  },
  {
    'product': 'pantalones',
    'price': 300
  },
  {
    'product': 'pantalones 2',
    'price': 200
  }
]

prices = list(map(lambda item: item['price'], items))
print(items)
print(prices)

def add_taxes(item):
  item['taxes'] = item['price'] * .19
  return item

new_items = list(map(add_taxes, items))
print(new_items)
print(items)

[{'product': 'camisa', 'price': 100}, {'product': 'pantalones', 'price': 300}, {'product': 'pantalones 2', 'price': 200}]
[100, 300, 200]
[{'product': 'camisa', 'price': 100, 'taxes': 19.0}, {'product': 'pantalones', 'price': 300, 'taxes': 57.0}, {'product': 'pantalones 2', 'price': 200, 'taxes': 38.0}]
[{'product': 'camisa', 'price': 100, 'taxes': 19.0}, {'product': 'pantalones', 'price': 300, 'taxes': 57.0}, {'product': 'pantalones 2', 'price': 200, 'taxes': 38.0}]

**PREGUNTA:**

¿por qué los dos objetos new_items e items, son iguales?, ¿podría causar algún error?, ¿cómo lo solucionaría?

# FILTER 
La función filter(), devuelve un valor que esta siendo iterado de la cual su resultado será el valor que se esta buscando en el filter.

In [37]:
numbers = [1, 2, 3, 4, 5]
new_numbers = list(filter(lambda x: x % 2 == 0, numbers))
print(new_numbers)  # Salida: [2, 4]

[2, 4]

In [38]:
data = {'a': 5, 'b': 15, 'c': 8, 'd': 20}
filtered_data = dict(filter(lambda item: item[1] > 10, data.items()))
print(filtered_data)  # Salida: {'b': 15, 'd': 20}

{'b': 15, 'd': 20}

# Reduce

La función reduce es una herramienta poderosa en Python, esencial para transformar una lista en un solo valor mediante la acumulación de sus elementos. Despuès de revisar map y filter, *reduce* completa la trilogía de funciones para la manipulación de listas. Es particularmente útil cuando necesitas realizar operaciones acumulativas como sumar todos los números en una lista o encontrar el máximo.

In [ ]:
import functools

numbers = [11, 12, 13, 14]

def accum(counter, item):
  print('counter => ',counter)
  print('item => ',item)
  return counter + item

result = functools.reduce(accum, numbers)

print(result)

counter =>  1
item =>  2
counter =>  3
item =>  3
counter =>  6
item =>  4
10

**PREGUNTA:**
Explica y documento el còdigo anterior ¿què realiza la funciòn **accum** y **reduce**?

In [56]:
print(counter)

NameError: name 'counter' is not defined